version: '2'
services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "~/.aerokube/selenoid/:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
      - TZ=America/Chicago
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "8", "-retry-count", "3", "-session-attempt-timeout", "5m"]
    ports:
      - "4444:4444"
  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "7777:7777"
    command: ["--listen", ":7777", "--selenoid-uri", "http://selenoid:4444"]
  qa:
    container_name: qa    
    build:
      context: .
      dockerfile: Dockerfile      
    network_mode: bridge
    depends_on:
      - selenoid
      - selenoid-ui
    environment:
      - TAGS=@SanityCheck
      - QA_ENV=${QA_ENV}
      - QA_OVERRIDE_ENV_PROMPT=${QA_OVERRIDE_ENV_PROMPT}
      - QA_CRAWL_N_LEVELS=${QA_CRAWL_N_LEVELS}
    links:
      - selenoid    
    command: ["${TAGS}"]
    volumes:
      - "./output:/app/output"
      - "./tests:/app/tests"      
      - "./pages:/app/pages"
